---

- name: MONIT | Create log directory
  file:
    path: "/var/lib/monit"
    state: directory
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"

- name: MONIT | Create id directory
  file:
    path: "{{ monit_log_dir }}"
    state: directory
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"

- name: MONIT | Create conf directories
  file:
    path: "{{ monit_conf_dir }}/{{ item }}/"
    state: directory
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
  with_items:
    - conf.d
    - monitrc.d

- name: MONIT | Copy configuration
  template:
    src: monitrc.j2
    dest: "{{ monit_conf_dir }}/monitrc"
    mode: 0600
  notify: restart monit
