---

- name: MONIT | Create log directory
  file:
    path: "{{ monit_lib_dir }}"
    state: directory
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    recurse: yes

- name: MONIT | Create id directory
  file:
    path: "{{ monit_log_dir }}"
    state: directory
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    recurse: yes

- name: MONIT | Create conf directories
  file:
    path: "{{ monit_conf_dir }}/{{ item }}/"
    state: directory
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    recurse: yes
  with_items:
    - conf.d
    - monitrc.d

- name: MONIT | Copy configuration
  template:
    src: monitrc.j2
    dest: "{{ monit_conf_dir }}/monitrc"
    mode: 0600
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
  notify: restart monit

- name: MONIT | Copy logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/monit
    mode: 0644
    owner: root
    group: root

- name: MONIT | Copy monitor files
  copy:
    src: "{{ item }}"
    dest: "{{ monit_conf_dir }}/monitrc.d/{{ item | basename }}"
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    mode: 0640
  with_fileglob:
    - "{{ monit_extra_servers_path }}/*"

- name: MONIT | Copy monitor templates
  template:
    src: "{{ item }}"
    dest: "{{ monit_conf_dir }}/monitrc.d/{{ item | basename }}"
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    mode: 0640
  with_fileglob:
    - "{{ monit_extra_servers_template_path }}/*"

- name: MONIT | Enable monitor
  file:
    src: "{{ monit_conf_dir }}/monitrc.d/{{ item | basename }}"
    dest: "{{ monit_conf_dir }}/conf.d/{{ item | basename }}"
    state: link
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
  with_fileglob:
    - "{{ monit_extra_servers_path }}/*"
    - "{{ monit_extra_servers_template_path }}/*"
  notify: reload monit
